---
version: "3.9"

networks:
  proxy_network:
    external: true
  staging_network:
    external: true

volumes:
  logs:
    # driver: local
  sessions:

services:
  app:
    # build:
    #   context: ./docker/php/8.1/
    #   dockerfile: Dockerfile
    #   tags:
    #     - rodrigocabral78/app-php:8.1.18-alpine
    #     - rodrigocabral78/app-php:latest
    #   args:
    #     GROUP: ${GROUP:-1001}:1001
    image: rodrigocabral78/app-php:8.1.18-alpine
    # image: php:8.1-alpine
    # command: php -S 0.0.0.0:8000 -t public
    # command: ./artisan serve -vvv --ansi --host=localhost --port=8000

    # ports:
    #   - 8080:8000
    # expose:
    #   - 8000
    extra_hosts:
      - host.docker.internal:host-gateway
    # network_mode: bridge
    networks:
      - proxy_network
      - staging_network

    working_dir: /var/www
    volumes:
      - .:/var/www
      - logs:/var/www/storage/logs
      - sessions:/var/www/storage/framework/sessions

    env_file: .env
    environment:
      # docker: "true"
      ###
      # nginx-proxy
      # https://github.com/nginx-proxy/nginx-proxy
      #
      - "VIRTUAL_HOST=app-laravel-docker-swarm-staging1.manaus.am.gov.br,app-laravel.docker-swarm-staging1.manaus.am.gov.br"
      - "VIRTUAL_PORT=8000"
      # - "VIRTUAL_PROTO=fastcgi"
      # - "VIRTUAL_ROOT=/var/www"
      ###
      # - "VIRTUAL_PROTO=https"
      # - "SERVER_TOKENS=on"
      # - "NETWORK_ACCESS=internal"
      # - "HTTPS_METHOD=redirect"
      # - "SSL_POLICY"
      # - "HSTS"
      # - "CERT_NAME"

    tty: true
    stdin_open: true
    # user: 0:998

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      # update_config:
      #   parallelism: 2
      #   delay: 10s
      #   order: stop-first
      # restart_policy:
      #   condition: on-failure
      #   delay: 5s
      #   max_attempts: 3
      #   window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 128M
